# Generated by Django 2.1 on 2019-04-12 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=255, unique_for_date='published')),
                ('mobile_number', models.CharField(max_length=10)),
                ('affected_county', models.CharField(max_length=10)),
                ('affected_persons', models.CharField(choices=[('children_under_5', 'Children Under 5 years'), ('children_under_18', 'Children Under 18 years'), ('adults_under_40', 'Adults Under 40 years'), ('adults_over_40', 'Children Over 40 years')], max_length=255)),
                ('case_description', models.TextField(max_length=500, unique=True)),
                ('supportive_image', models.ImageField(upload_to='cases_images')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
