# Generated by Django 2.1 on 2019-04-12 11:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=100)),
                ('county_code', models.CharField(max_length=100)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_title', models.CharField(max_length=250)),
                ('target_population', models.CharField(max_length=250)),
                ('running_from', models.DateField()),
                ('running_to', models.DateField()),
                ('thumbnail', models.ImageField(upload_to='open_campaigns')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('registration_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='Open', max_length=250)),
                ('voting_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='Open', max_length=250)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.County')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_type', models.CharField(choices=[('group', 'Group'), ('organization', 'Organization')], max_length=100)),
                ('organization_or_group_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=255)),
                ('mobile_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('group_or_org_description', models.TextField(help_text='Briefly describe your group/organization', max_length=1000)),
                ('supporting_image', models.ImageField(upload_to='campaign_images')),
                ('group_or_org_profile', models.FileField(help_text='Upload a pdf of your profile', upload_to='campaign_profiles')),
                ('status', models.CharField(choices=[('won', 'Won'), ('lost', 'Lost'), ('waiting', 'Waiting')], default='waiting', max_length=255)),
                ('total_votes', models.IntegerField(blank=True, default=0, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.County')),
                ('open_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.OpenCampaign')),
            ],
            options={
                'verbose_name_plural': 'Submitted Campaigns',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_campaign', models.CharField(max_length=250)),
                ('organization_or_group_name', models.CharField(max_length=255)),
                ('voter_name', models.CharField(max_length=250)),
                ('voter_id', models.IntegerField()),
                ('vote_time', models.CharField(default='', max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Votes',
            },
        ),
    ]
